config/routes.rb
Rails.application.routes.draw do
  resources :items
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
	resources :users
	resources :sessions

	get 'signup', to: 'users#new' , as:'signup'
	post 'register', to: 'users#create' , as:'register'
	get 'userInfo', to: 'users#get', as: 'userInfo'
	get 'signin', to: 'sessions#new', as: 'signin'
	post 'login', to: 'sessions#create' , as:'login'
	post 'history', to: 'sessions#history' , as:'history'
	post 'notifications', to: 'sessions#notifications' , as:'notifications'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  serialize :history, Array
  serialize :notifications, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :null_session
	before_action :authenticate_request
	attr_reader :current_user
  
	private
  
	def authenticate_request
	  @current_user = AuthorizeApiRequest.call(request.headers).result
	  render json: { error: 'Not Authorized' }, status: 401 unless @current_user
	end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = RubyAuthSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?
    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :description)
    end
end

app/controllers/sessions_controller.rb
require 'net/ldap'

class SessionsController < ApplicationController
	skip_before_action :authenticate_request
	def new
	end

	def history
		params.permit(:email, :history => [])
		email = params[:email]		
		history =  params[:history]#.split(",")
		user = User.find_by(:email => email)
		if user
			user.update_attribute(:history, history)
			puts params[:history]
			# user.history = params[:history]
			response = {
				:history => "Success: history updated"
			}
		else
			response = {
				:history => "Error: history couldn't be created"
			}			
		end
		render json: response
	end

	def notifications
		#params.permit(:email, :notifications => [])
		email = params[:email]		
		notifications =  params[:notifications]#.split(",")
		user = User.find_by(:email => email)
		if user
			user.update_attribute(:notifications, notifications)
			puts params[:notifications]
			# user.history = params[:history]
			response = {
				:notifications => "Success: notifications updated"
			}
		else
			response = {
				:notifications => "Error: notifications couldn't be created"
			}			
		end
		render json: response
	end

	def create
		email = params[:email]
		puts email
		password = params[:password]
		puts password
		ldap      = Net::LDAP.new
		ldap.host = LDAP_CONFIG['host']
		puts ldap.host
		ldap.port = LDAP_CONFIG['port']
		puts ldap.port
		ldap.authenticate "cn=#{email},ou=sa,dc=arqsoft,dc=unal,dc=edu,dc=co", password
		bound = ldap.bind
	
		if bound
			puts "Got it"
		else
			render json: error= {
				:error => "Error: user is not in organization (LDAP)"
			}
			return ""
		end

		userFound = User.find_by(:email => params[:email])
		command = AuthenticateUser.call(params[:email], params[:password])

		if command.success?
			userInfo = {
				:user => userFound,
				:auth_token => command.result
			}
		  render json: userInfo
		  #render json: { auth_token: command.result }
		else
			render json: error= {
				:error => "Error: invalid credentials"
			}
		  #render json: { error: command.errors }, status: :unauthorized
		end
	end

	def destroy
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :authenticate_request

	def new
	end

	def get
		email = params[:email]
		user = User.find_by(:email => email)
		if user
			response = user
		else
			response =  "Error: there is no user with such email"
		end
		render json: response
	end

	def create
		email = params[:email]
		password = params[:password]
		username = params[:username]
		user = User.find_by(:email => email)
		if user
			response = "Error: There is already a user with that email"
					
		else
			User.create(
				:email => email,
				:password => password,
				:password_confirmation => password,
				#:password_digest => password,
				:username => username,
				:history => []
			)
			user = User.find_by(:email => email)	
			if user
				response = "Success: User successfully registered"
			else
				response = "Error: There was an error in the backend registering the user"		
			end
		end
		render json: response
	end

	def destroy
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= item.description %>
  </p>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyAuth</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<% if @success %>
	<p>Your account was created</p>
	<a href="<%= signin_path %>">Click here to login</a>
<% end %>

<h1>Sign up</h1>

<form method="POST" action="<%= register_path %>">
	
	<label for="username">Username</label>
	<input type="email" name="username" id="username" required>
	<label for="userpassword">Password</label>
	<input type="password" name="userpassword" id="userpassword" required>
	<input type="submit" value="register">
</form>